package etcd

import (
	"strings"
	"testing"

	"k8s-health-tui/internal/config"
)

const sample = `
===DIST
rke2
===HOST
cp-1
===PATHS
ca=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt
cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt
key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key
endpoint=https://127.0.0.1:2379
datadir=/var/lib/rancher/rke2/server/db/etcd
===SOURCE
static-pod /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
rke2-config /etc/rancher/rke2/config.yaml
etcd-config /var/lib/rancher/rke2/server/db/etcd/config (generated by rke2)
===RKE2CONFIG
/etc/rancher/rke2/config.yaml: etcd-snapshot-schedule-cron: 0 */6 * * *
/etc/rancher/rke2/config.yaml: etcd-s3: true
/etc/rancher/rke2/config.yaml: etcd-s3-config-secret: rke2-s3
===CONFIGDUMP
--- /var/lib/rancher/rke2/server/db/etcd/config
client-transport-security:
  client-cert-auth: true
peer-transport-security:
  client-cert-auth: true
quota-backend-bytes: 2147483648
===HEALTH
{"health":"true","reason":""}
===METRICS
etcd_server_has_leader 1
etcd_server_is_leader 1
etcd_server_leader_changes_seen_total 3
etcd_mvcc_db_total_size_in_bytes 5.0e+07
etcd_mvcc_db_total_size_in_use_in_bytes 2.0e+07
etcd_server_quota_backend_bytes 2.147483648e+09
etcd_disk_wal_fsync_duration_seconds_sum 10
etcd_disk_wal_fsync_duration_seconds_count 5000
etcd_disk_backend_commit_duration_seconds_sum 1
etcd_disk_backend_commit_duration_seconds_count 100
etcd_server_version{server_version="3.5.16"} 1
etcd_cluster_version{cluster_version="3.5"} 1
etcd_server_proposals_failed_total 0
etcd_server_proposals_pending 0
===ETCDCTL
via=crictl abc123
---MEMBERS
{"header":{"cluster_id":1,"member_id":2},"members":[{"ID":11,"name":"cp-1","peerURLs":["https://10.0.0.1:2380"],"clientURLs":["https://10.0.0.1:2379"]},{"ID":12,"name":"cp-2","peerURLs":["https://10.0.0.2:2380"],"clientURLs":["https://10.0.0.2:2379"],"isLearner":true}]}

---STATUS
[{"Endpoint":"https://10.0.0.1:2379","Status":{"header":{"cluster_id":1,"member_id":11,"raft_term":7},"version":"3.5.16","dbSize":50000000,"leader":11,"raftIndex":1234,"raftTerm":7,"dbSizeInUse":20000000}},{"Endpoint":"https://10.0.0.2:2379","Status":{"header":{"cluster_id":1,"member_id":12,"raft_term":7},"version":"3.5.16","dbSize":50000000,"leader":11,"raftIndex":1234,"raftTerm":7,"errors":["boom"]}}]

---ALARMS
{"header":{"cluster_id":1},"alarms":[{"memberID":11,"alarm":1}]}

===DATADIR
/var/lib/rancher/rke2/server/db/etcd
123456
/dev/sdb1 200000000 20000000 180000000 10% /var/lib/rancher
===SNAPSHOTS
--- /var/lib/rancher/rke2/server/db/snapshots
5000|1726600000|/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-cp-1-1726600000
6000|1726650000|/var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-cp-1-1726650000
--- /var/lib/rancher/rke2/server/db/snapshots
1|1|/dup
===BACKUPHINTS
timer: Wed 2024-09-18 12:00:00 UTC 1h left etcd-backup.timer
===END
`

func TestParse(t *testing.T) {
	p := Parse("cp-1", sample)
	if p.Dist != "rke2" || p.Endpoint != "https://127.0.0.1:2379" || p.DataDir != "/var/lib/rancher/rke2/server/db/etcd" {
		t.Fatalf("basics: %+v", p)
	}
	if len(p.Sources) != 3 {
		t.Errorf("sources: %v", p.Sources)
	}
	if p.RKE2Config["etcd-snapshot-schedule-cron"] != "0 */6 * * *" || p.RKE2Config["etcd-s3-config-secret"] != "rke2-s3" {
		t.Errorf("rke2 config: %v", p.RKE2Config)
	}
	if len(p.ConfigDump) != 1 || !strings.Contains(p.ConfigDump[0].Content, "quota-backend-bytes") {
		t.Errorf("config dump: %+v", p.ConfigDump)
	}
	if p.Health == nil || !p.Health.Healthy {
		t.Errorf("health: %+v", p.Health)
	}
	m := p.Metrics
	if m == nil || !m.HasLeader || !m.IsLeader || m.LeaderChanges != 3 || m.DBSize != 5e7 || m.Quota != 2147483648 {
		t.Fatalf("metrics: %+v", m)
	}
	if m.WalFsyncAvgMs != 2 || m.BackendCommitAvgMs != 10 || m.ServerVersion != "3.5.16" || m.ClusterVersion != "3.5" {
		t.Errorf("metrics derived: %+v", m)
	}
	if p.EtcdctlVia != "crictl abc123" || len(p.Members) != 2 || p.Members[0].ID != "b" || !p.Members[1].IsLearner {
		t.Errorf("members: via=%q %+v", p.EtcdctlVia, p.Members)
	}
	if len(p.Statuses) != 2 || p.Statuses[0].Leader != "b" || p.Statuses[0].MemberID != "b" || p.Statuses[0].RaftTerm != 7 || len(p.Statuses[1].Errors) != 1 {
		t.Errorf("statuses: %+v", p.Statuses)
	}
	if st := p.Status("c"); st == nil || st.Endpoint != "https://10.0.0.2:2379" {
		t.Errorf("status lookup: %+v", st)
	}
	if len(p.Alarms) != 1 || p.Alarms[0].Type != "NOSPACE" || p.Alarms[0].MemberID != "b" {
		t.Errorf("alarms: %+v", p.Alarms)
	}
	if p.DataDirUsedKB != 123456 || p.DataDirFS == nil || p.DataDirFS.UsePct != 10 || p.DataDirFS.Mount != "/var/lib/rancher" {
		t.Errorf("datadir: %d %+v", p.DataDirUsedKB, p.DataDirFS)
	}
	if len(p.SnapshotDirs) != 1 || len(p.SnapshotDirs[0].Files) != 2 || p.SnapshotDirs[0].Files[0].Name != "etcd-snapshot-cp-1-1726650000" {
		t.Errorf("snapshots: %+v", p.SnapshotDirs)
	}
	if f, dir, ok := p.LatestSnapshot(); !ok || f.Size != 6000 || dir != "/var/lib/rancher/rke2/server/db/snapshots" {
		t.Errorf("latest: %+v %s %v", f, dir, ok)
	}
	if len(p.BackupHints) != 1 {
		t.Errorf("hints: %v", p.BackupHints)
	}
}

func TestParseGateway(t *testing.T) {
	raw := `===DIST
rke2
===PATHS
endpoint=https://127.0.0.1:2379
missing=/nope.crt
===ETCDCTL
via=grpc-gateway
diag=no running etcd container found via /var/lib/rancher/rke2/bin/crictl -r unix:///run/k3s/containerd/containerd.sock
---MEMBERS
{"header":{"cluster_id":"1","member_id":"11","raft_term":"7"},"members":[{"ID":"11","name":"cp-1","peerURLs":["https://10.0.0.1:2380"],"clientURLs":["https://10.0.0.1:2379"]},{"ID":"12345678901234567890","name":"cp-2","peerURLs":["https://10.0.0.2:2380"],"clientURLs":["https://10.0.0.2:2379"]}]}

---GWSTATUS
{"header":{"cluster_id":"1","member_id":"11","raft_term":"7"},"version":"3.5.16","dbSize":"50000000","leader":"11","raftIndex":"1234","raftTerm":"7","dbSizeInUse":"20000000"}

---GWALARMS
{"header":{"cluster_id":"1"},"alarms":[{"memberID":"11","alarm":"NOSPACE"}]}
===END
`
	p := Parse("cp-1", raw)
	if p.EtcdctlVia != "grpc-gateway" || !strings.HasPrefix(p.EtcdctlDiag, "no running etcd container") {
		t.Errorf("via/diag: %q %q", p.EtcdctlVia, p.EtcdctlDiag)
	}
	if len(p.Missing) != 1 || p.Missing[0] != "/nope.crt" {
		t.Errorf("missing: %v", p.Missing)
	}
	if len(p.Members) != 2 || p.Members[0].ID != "b" || p.Members[1].ID != "ab54a98ceb1f0ad2" {
		t.Errorf("members: %+v", p.Members)
	}
	if len(p.Statuses) != 1 || p.Statuses[0].MemberID != "b" || p.Statuses[0].Leader != "b" || p.Statuses[0].DBSize != 50000000 || p.Statuses[0].Version != "3.5.16" {
		t.Errorf("gateway status: %+v", p.Statuses)
	}
	if len(p.Alarms) != 1 || p.Alarms[0].Type != "NOSPACE" || p.Alarms[0].MemberID != "b" {
		t.Errorf("alarms: %+v", p.Alarms)
	}
}

func TestParseNoEtcd(t *testing.T) {
	p := Parse("w-1", "===DIST\nunknown\n===HOST\nw-1\n===PATHS\nca=\ncert=\nkey=\nendpoint=https://127.0.0.1:2379\ndatadir=\n===SOURCE\n===HEALTH\n===METRICS\n===ETCDCTL\nvia=none\n===END\n")
	if p.Dist != "unknown" || p.Health != nil || p.Metrics != nil || len(p.Members) != 0 {
		t.Errorf("unexpected: %+v", p)
	}
}

func TestScriptSanitises(t *testing.T) {
	s := Script(config.Etcd{BackupDirs: []string{"/backup/etcd", "/bad'; rm -rf /"}, Endpoint: "https://10.0.0.5:2379"})
	if !strings.Contains(s, "EXTRA_DIRS='/backup/etcd /badrm-rf/'") {
		t.Errorf("dirs not sanitised: %s", s[:200])
	}
	if !strings.Contains(s, "EP_OVERRIDE='https://10.0.0.5:2379'") {
		t.Errorf("endpoint override missing")
	}
}

func TestHealthFallback(t *testing.T) {
	h := parseHealth("curl-missing")
	if h.Healthy || h.Reason != "curl not installed on node" {
		t.Errorf("%+v", h)
	}
	h = parseHealth(`{"health":"false","reason":"NOSPACE"}`)
	if h.Healthy || h.Reason != "NOSPACE" {
		t.Errorf("%+v", h)
	}
}
